bjjblog/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = staticfiles_urlpatterns() \
    + [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^', include('posts.urls', namespace='posts')),


    ]

posts/urls.py
from django.conf.urls import url, include

from .views import PostListView, PostDetailView, PassingListView, OpenGuardListView, HalfGuardListView

app_name = 'posts'

urlpatterns = [
    url(r'(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    url(r'^passing/', PassingListView.as_view(), name='passinglist'),
    url(r'^openguard/', OpenGuardListView.as_view(), name='openguardlist'),
    url(r'^halfguard/', HalfGuardListView.as_view(), name='halfguardlist'),
    url(r'^', PostListView.as_view(), name='list'),


]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse

from embed_video.fields import EmbedVideoField


class Post(models.Model):
    author = models.CharField(max_length=50)
    technique_type = models.CharField(max_length=50)
    description =  models.TextField(max_length=3000)
    pub_date = models.DateTimeField()
    title = models.CharField(max_length=250)
    video = EmbedVideoField()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

posts/views.py
from django.views.generic import ListView, DetailView

from .models import Post


class PostListView(ListView):
    model = Post
    paginate_by = 10
    def get_queryset(self):
        queryset = Post.objects.order_by('-pub_date').filter(author__startswith='Jason')
        return queryset

class PostDetailView(DetailView):
    model = Post


class PassingListView(ListView):
    model = Post
    paginate_by = 10
    template_name = 'posts/technique_list.html'
    def get_queryset(self):
        queryset = Post.objects.order_by('-pub_date').filter(technique_type__contains='Pass')
        return queryset

class OpenGuardListView(ListView):
    model = Post
    paginate_by = 10
    template_name = 'posts/technique_list.html'
    def get_queryset(self):
        queryset = Post.objects.order_by('-pub_date').filter(technique_type__contains='Open')
        return queryset

class HalfGuardListView(ListView):
    model = Post
    paginate_by = 10
    template_name = 'posts/technique_list.html'
    def get_queryset(self):
        queryset = Post.objects.order_by('-pub_date').filter(technique_type__contains='Half')
        return queryset

bjjblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Goyer's Journal</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>


    .detail {
  line-height: 0;
  font-size: 0;
}

/* Sets the font and line height correctly for the paragraph of text */
.detail {
  line-height: 16px;
  font-size: 16px;
}
    body {
      font-size: 32px;
    }

    h1 {
      font-size: 64px;
      margin: 20px 5px;
    }

    .admin {
    margin-top: 10px;

}
    </style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'posts:list' %}">Goyer's Blog</a>

        </div>
        <button type="button" class="btn pull-right admin"> <a href="{% url 'admin:index' %}">Admin</a></button>
        <div class="btn-group">

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Techniques <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'posts:passinglist' %}">Passing</a></li>
                    <li><a href="#">Takedowns</a></li>
                    <li><a href="#">Side Control</a></li>
                    <li><a href="#">Mount</a></li>
                    <li><a href="#">Closed Guard</a></li>
                    <li><a href="{% url 'posts:openguardlist' %}">Open Guard</a></li>
                    <li><a href="{% url 'posts:halfguardlist' %}">Half Guard</a></li>
                    <li><a href="#">Back</a></li>
                </ul>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Drilling <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Passing</a></li>
                    <li><a href="#">Sweeping</a></li>
                </ul>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Rolling <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">BMA</a></li>
                    <li><a href="#">Other</a></li>

                </ul>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Competition <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">IBJJF</a></li>
                    <li><a href="#">Good Fight</a></li>
                    <li><a href="#">US Grappling</a></li>
                    <li><a href="#">Other</a></li>
            </div>



        </div>
    </div>
</nav>

<div class="container">

    {% block content %}{% endblock %}

</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/posts/post_detail.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}

<h1>
  {{ post.title }}
  <a href="{% url "posts:list" %}" class="pull-right"><small>Home</small></a>

</h1>

{% video post.video as my_video %}

  {% video my_video "large" %}
{% endvideo %}

{% endblock %}

posts/templates/posts/post_list.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}



<h1>BJJ Journal Posts</h1>
<table class="table">
  {% for post in object_list %}
  <tr>
    {% video post.video as video %}
    <td><font size="4"><pre>{{ post.pub_date_pretty }}</pre> </font> </td>
    <td class="detail"><font size="4">{{ post.description }} </font></td>
    <td><a href="{{ post.get_absolute_url }}"><img src="{{ video.thumbnail }}" width=240 height=180 class="img-rounded"></a></td>
    {% endvideo %}
  </tr>

  {% endfor %}
</table>

<ul class="pager">
  {% if page_obj.has_previous %}
  <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Older</a></li>
  {% endif %}
  {% if page_obj.has_next %}
  <li class="next"><a href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a></li>
  {% endif %}
</ul>
{% endblock %}

posts/templates/posts/technique_list.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}
<h2> {{ object_list.0.technique_type }}</h2>
<table class="table">
  {% for technique in post_list %}
  <tr>
    {% video technique.video as video %}
    <td class = detail> <pre>{{ technique.title }}</pre>
      {{ technique.description }} </td>
    <td><a href="{{ technique.get_absolute_url }}"><img src="{{ video.thumbnail }}" width=240 height=190 class="img-rounded"></a></td>
    {% endvideo %}
  </tr>

  {% endfor %}
</table>

<ul class="pager">
  {% if page_obj.has_previous %}
  <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Older</a></li>
  {% endif %}
  {% if page_obj.has_next %}
  <li class="next"><a href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a></li>
  {% endif %}
</ul>
{% endblock %}